#!/usr/bin/env bash

# go to root of the project
if ! [ -z "$FORNIX_FOLDER" ]
then
    cd "$FORNIX_FOLDER"
fi
# go to correct local folder
cd src/pytransit/doc
# make sure dependency exists
pip install sphinx-rtd-theme 1>/dev/null
# try building the docs and starting the server
make clean && make html && echo 'http://localhost:8000/' && python3 -m http.server --directory ./build/html